### ISSUE TITLE
How to use longtable when using tagset=latex

### ISSUE THREAD

**Issue by larsvilhuber** [tiarno/StatRep#2]
Long tables are not wrapping, because it looks like the latex tagset doesn't use longfigure or longtable. 

Replicability: Generate a dataset with more than 50 variables, print out a proc contents.

`\begin{Sascode}[store=ehf_zz_phf,program]
        %macro mine;
           data test;
             %do i = 1 %to 50;
              var&i. = 1; label var&i. = "Variable &i.";
            %end;
           run;
    proc contents data=test";
    run;
\end{Sascode}
\Listing[store=ehf_zz_phf,options=table,objects=Variables,
caption={EHF\_ZZ\_PHF}]{ehfzzphf}`

**Comment by larsvilhuber** [comment]
I've verified that it is not the specific document I'm using that is the cause of the problem. 
1. Downloaded statrep.zip from SAS website
2. Extracted and compiled quickstart.tex - works.
3. Add to last lines (before \end{document}) the code from here: https://gist.github.com/larsvilhuber/b8dbd528ce192660166e9b6301df826b
4. Compiled, ran SAS code, compiled.

The resulting file (see attached) does not wrap the table generated by the proc contents across pages.
[quickstart.pdf](https://github.com/tiarno/StatRep/files/455806/quickstart.pdf)

**Comment by tiarno** [comment]
Hi, Appendix C in the statrepmanual.pdf describes this: unfortunately there is only limited support for SAS-generated LaTeX output. 

Section C.3 describes one possible workaround for shifting wide outputs. 

If the table will not fit on the page at all you must change to 'listing' output style instead of 'latex'. 

Another workaround might be to shorten the output table itself (second method described in Section 13.2).
